### ISSUE TITLE
New processor features

### ISSUE THREAD

**Issue by DrNochi** [Projektstudium-Mikroprozessor/Super32#20]
- Added LI, NAND, NOR, SHL, SLR, SAR instructions
  - **li r1, value(r2)**: Load immediate (r1 = value + r2), _[000011|r2|r1|value]_
  - **nand rd, r1, r2**: Bitwise NAND (rd = ~(r1 & r2)), _[000000|r1|r2|rd|xxx|1011]_
  - **nor rd, r1, r2**: Bitwise NOR (rd = ~(r1 | r2)), _[000000|r1|r2|rd|xxx|1010]_
  - **shl rd, r1, r2**: Left shift (rd = r1 >> r2), _[000000|r1|r2|rd|xxx|1100]_
  - **slr rd, r1, r2**: Logical right shift (rd = r1 << r2), _[000000|r1|r2|rd|xxx|1110]_
  - **sar rd, r1, r2**: Arithmetical right shift (rd = r1 << r2), _[000000|r1|r2|rd|xxx|1111]_
- Hardwired **r30** to constant _0_
- Hardwired **r31** to constant _1_

See Projektstudium-Mikroprozessor/Mikroprozessor#4

Edit: Prof. Gerlach suggested using r30 & r31 for hard-wired constants

**Comment by DrNochi** [comment]
One could add pseudo instructions that are translated to acutal instructions using r0 as dummy register, e.g.:

- **mov rd, rs** => add rd, rs, r30
- **nop** => add r30, r30, r30, this actually equals the binary number 0x00'00'00'00
- **jmp offset** => beq r30, r30, offset
- **clr rd** => add rd, r30, r30 (alternative opcode mnemonic: nul rd)
- **neg rd** => sub rd, r30, rd
- **neg rd, rs** => sub rd, r30, rs
- **li rd, value** => li rd, value(r30)
- ...

**Comment by MaxAtoms** [comment]
This should be rather simple once we get the emulation to work reliably.
I will look into it when #21 is fixed and #1 is implemented :grin:

**Comment by DrNochi** [comment]
Closing this issue as part of it has been implemented... Pseudo instructions are tracked in #59
