### ISSUE TITLE
Incorrect line highlighting when lines are wrapped

### ISSUE THREAD

**Issue by MaxAtoms** [Projektstudium-Mikroprozessor/Super32#64]
**Description:** In Debugging mode the wrong lines are highlighted when there are line wraps present

**Steps to reproduce:**
1) Open a code file
2) Resize the window so that some lines are automatically wrapped
3) Step through the code step-by-step

**Expected Result:** Line wraps should not affect debugging behaviour. The correct lines should get highlighted.

**Comment by MaxAtoms** [comment]
`findBlockByNumber` should be used instead of `findBlockByLineNumber`.
I was wondering which method is the correct one and the latter sounded correct.
The documentation is not really descriptive.

![QTextDocumentLineNumber](https://user-images.githubusercontent.com/7847075/90954477-dc34ab80-e474-11ea-9a57-2ffcaaa0bcd7.png)

See: https://doc.qt.io/qt-5/qtextdocument.html#findBlockByLineNumber

**Comment by DrNochi** [comment]
Fixed by pull request #76
