### ISSUE TITLE
Always highlight source and destination (for register as well as memory)

### ISSUE THREAD

**Issue by MaxAtoms** [Projektstudium-Mikroprozessor/Super32#65]
Currently we highlight source and destination addresses in memory.
We should also highlight the source register, not only destination.
For ALU commands we should highlight source registers as well as destination registers.

**Comment by MaxAtoms** [comment]
What is the expected behavior for `BEQ` commands?
Should we also highlight registers that are used for calculating the offset (e.g. `R3` in a command like `SW R1,result1(R3)`)?

@DrNochi

**Comment by DrNochi** [comment]
I'd leave it as it is right now... We can change it later if the current behaviour turns out to be unintuitive/"unexpected"
