### ISSUE TITLE
BEQ commands for START and END directive are incorrect

### ISSUE THREAD

**Issue by MaxAtoms** [Projektstudium-Mikroprozessor/Super32#68]
**Description:** START and END directive should be replaced by a unconditional branch command. Currently, two different registers are being compared instead.

**Steps to reproduce:**

1. Open a code file
2. Run the assembler by running the code
3. Inspect the first and last commands in memory

**Expected Result:** The BEQ commands should compare R30 with R30

**Comment by DrNochi** [comment]
Fixed by pull request #73
