### ISSUE TITLE
Allow usage of hexadecimal numbers as addresses

### ISSUE THREAD

**Issue by MaxAtoms** [Projektstudium-Mikroprozessor/Super32#69]
As a user I want to be able to use hexadecimal addresses so that I can specify memory locations more easily.
Usage of `$` character to denote a hexadecimal number in contrast to a decimal number.

Example:

`LW R1,$18(R30)` should be the same as `LW R1,24(R30)`

**Comment by DrNochi** [comment]
Implemented in pull request #75
