### ISSUE TITLE
Improve GUI proportions

### ISSUE THREAD

**Issue by MaxAtoms** [Projektstudium-Mikroprozessor/Super32#70]
- [x] Register input fields should only be wide enough to display their content
- [x] Symbol table should be slimmer (can be realized together with #39)
- [X] Keep scrolling position in memory widget (currently it is reset to the top-left after each debugging step)
- [x] Give the memory widget a fixed width so that all 32 bits of a row are visible

**Comment by DrNochi** [comment]
Done #77
